main: com.sebiseb15.beaconrange.BeaconRange
name: BeaconRange
version: "${VERSION}"
api-version: "1.21"
author: Sebiseb15
description: permets de configurer le rayon des beacons
commands:
  beaconrange:
    description: permets de modifier le rayon des beacons selon le tier
    usage: /beacongrange <set|get> <tier> <radius>
    Permissions: beaconrange.admin